name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next
        
    - name: Build with Next.js for GitHub Pages
      run: |
        echo "Starting build process..."
        echo "Environment: GITHUB_PAGES=$GITHUB_PAGES"
        echo "Removing any compiled next.config.js to ensure TypeScript config is used..."
        rm -f next.config.js
        echo "Checking Next.js configuration..."
        cat next.config.ts | head -20
        echo "Running Next.js build..."
        npx next build
        echo "Build completed. Checking for out directory..."
        if [ -d "./out" ]; then
          echo "✅ out directory created successfully"
          ls -la ./out/
        elif [ -d "./.next" ]; then
          echo "⚠️ .next directory exists but out directory not created"
          echo "Next.js may not be configured for static export properly"
          echo "Build output indicates static export did not run"
          echo "Current directory contents:"
          ls -la ./
          exit 1
        else
          echo "❌ Neither out nor .next directory was created"
          echo "Current directory contents:"
          ls -la ./
          exit 1
        fi
      env:
        GITHUB_PAGES: true
        DISABLE_ESLINT_PLUGIN: true
        ESLINT_NO_DEV_ERRORS: true
        NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
        
    - name: Add .nojekyll file
      run: |
        touch ./out/.nojekyll
        echo "✅ .nojekyll file created successfully"
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4